services:
  php:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: robot-php
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    user: "${UID}:${GID}"
    networks:
      - robot_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: robot-nginx
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - robot_network
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: robot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: robot
      MYSQL_USER: robot
      MYSQL_PASSWORD: robot
    volumes:
      - robot_mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - robot_network

volumes:
  robot_mysql_data:

networks:
  robot_network:
